# Generated by Django 5.2.12 on 2026-03-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_clubs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubs',
            options={'verbose_name': 'Club'},
        ),
    ]
